#!/bin/bash

# Job name:
#SBATCH --job-name=A585Convert
#
# Project:
#
# Wall time limit:
#SBATCH --time=02-00:00:00
#
# Other parameters:
#SBATCH --mem-per-cpu=3G
#SBATCH	--ntasks=16
## Set up job environment:
set -o errexit  # Exit the script on any error
set -o nounset  # Treat any unset variables as an error

module --quiet purge  # Reset the modules to the system default

## Do some work:
bash /storage/Jamesfl/ReplG_2024/BAMtoFASTQ.sh Ga55_m84108_240416_193028_s4.fail_reads.bc2009.bam Ga55_m84108_240416_193028_s4.fail_reads.bc2009.fastq

