#!/bin/bash

# Job name:
#SBATCH --job-name=Ga55genomeassembly0524
#
# Project:
#
# Wall time limit:
#SBATCH --time=03-00:00:00
#
# Other parameters:
#SBATCH --mem-per-cpu=5G
#SBATCH	--ntasks=64
## Set up job environment:
set -o errexit  # Exit the script on any error
set -o nounset  # Treat any unset variables as an error

module --quiet purge  # Reset the modules to the system default

## Do some work:
sh AssemblyHifiAsm_QualityAssessment_v1.7.sh Ga55_allHifireads.fastq Query_Polychaeta_ProtMito.fasta 1e-20 10 64 5G 274M > Ga55.HifiQAPipeline.out


